### ISSUE TITLE
Dataset folders: data vs. demo_sequences vs. ros_sequences

### ISSUE THREAD

**Issue by ptoews** [uulm-mrm/aduulm_dataset_tools#1]
Before I download the full dataset I'd like to know what the difference between these three folders is. According to the README the format is different, but `data` seems to be a lot smaller, so this is probably just a subset?
And `demo_sequences` apparently contains only bags without weather categorization. Is this only data in clear weather?
Which of the three folders contain the whole dataset, and which part is missing in each?

Thanks in advance.

**Comment by markusschoen** [comment]
- The `data` directory contains all annotated data samples in the dataset. This directory contains all necessary data for single-shot segmentation training.
- The `ros_sequences` directory contains rosbag files. They can be used to extract image frames before and after annotated frames. These sequences can be used for recurrent neural network training.
- The `demo_sequences` directory contains raw recorded rosbags of our test vehicle. Actually, the file names contain the weather categorization. They can be used to get a first shot of the data using ROS-Tools, i.e. RViz, but do not contain relevant data for the tasks.

Hope this answers your question.

**Comment by ptoews** [comment]
Thanks, still a few questions:
If `demo_sequences` contains raw data, does that mean `ros_sequences` is somehow preprocessed? Or does it only contain (RGB) images? Are these two sets from different recordings?

I'm specifically interested in lidar data currently if that's relevant.

**Comment by markusschoen** [comment]
`ros_sequences` also contains raw data. Both, `ros_sequences` and `demo_sequences` contain mono images, lidar scans and IMU data. `ros_sequences` are processed in the sense, that we provide one small sequence for each annotated frame, which contains only a few context frames with respect to this specific annotated frame. I think, this will be clear, once the download is available and you can have a look at the actual data.

**Comment by ptoews** [comment]
Okay, thank you!
